#ifndef MULTITHREADING_COURSE__UNNAMEDPIPESPROCESS_HPP_
#define MULTITHREADING_COURSE__UNNAMEDPIPESPROCESS_HPP_

#include "IProcess.hpp"

class UnnamedPipesProcess : public IProcess {

};

#endif //MULTITHREADING_COURSE__UNNAMEDPIPESPROCESS_HPP_
